modLoader="javafml"
loaderVersion="${fml_version}"
license="MIT"
issueTrackerURL="https://github.com/rawchickenNEG/CopperAndCrystalReborn/issues"

[[mods]]
modId="copper_and_crystal_reborn"
version="${mod_version}"
displayName="Copper And Crystal Reborn"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/rawchickenNEG/CopperAndCrystalReborn"
logoFile="pack.png"
credits="Thanks for LimonBlaze on code contributions"
authors="rawchickenNEG"
description=""

[[dependencies.copper_and_crystal_reborn]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies.copper_and_crystal_reborn]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version}"
    ordering="NONE"
    side="BOTH"
