@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.rawchickenneg.copperandcrystalreborn.util;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;