@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.rawchickenneg.copperandcrystalreborn.common.registry;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;