@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.rawchickenneg.copperandcrystalreborn.client.render;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;